#!/bin/sh

while read fn ; do
    if [ -f "$fn" ] ; then
        echo "$fn OK."
    else
        echo "Problem with $fn."
    fi
done <<EOF
14_ounce_can_whole_tomatoes.jpg
15_ounce_cans_red_kidney_beans.jpg
15oz_low_fat_ricotta_cheese.jpg
1_lb_turkey_burger.jpg
4_*_4oz_boneless,_skinless_chicken_breast_halves.jpg
Adirondaks_lime_water.jpg
Adirondaks_strawberry_water.jpg
Alfredo_sauce.jpg
Antacid.jpg
Bag_of_Morton's_Salt_for_water_filter.jpg
Bananas.jpg
Bare_Essentials_Granola.jpg
Bear_Naked_Tripple_Berry_granola.jpg
Beefaroni/Beefagetti.jpg
Ben.jpg
Ben_an.jpg
Ben_and_Jerry's.jpg
Ben_and_Jerry''s.jpg
Blueberries.jpg
Bubbling_Lime_Water.jpg
Can_of_tomato_sauce.jpg
Can_of_whole_corn_kernels.jpg
Chicken_Cordon_Bleu_dumplings.jpg
Chris'_cereal.jpg
Clorox_Cleanup.jpg
Coffee_Mate_Italian_Sweet_Cream.jpg
Crest_gel_toothpaste.jpg
Diet_cranberry_juice.jpg
Diet_Decaf_Coke.jpg
Dishwasher_detergent.jpg
Dog_food.jpg
Dog_treats.jpg
Dried_apricot.jpg
eels.jpg
Egg_substitute.jpg
English_muffins.jpg
Fabric_Softener.jpg
Fat_free_half_&_half.jpg
Fresca.jpg
Frosted_Mini_Wheats.jpg
Frozen_dinners.jpg
Fruit_for_Jacque.jpg
Garbage_bags.jpg
Ginger.jpg
Granny_Smith_Apples.jpg
Greek_yogurt_of_varying_flavors.jpg
Half_gallon_of_1%_milk.jpg
Hollandaise_sauce.jpg
Honey.jpg
Hot_dog_rolls.jpg
Hot_dogs.jpg
Ibuprofin.jpg
ice.jpg
Jacque's_cereal.jpg
Large_Grade_A_eggs.jpg
Lasagna.jpg
Lemon_Splenda_Coke.jpg
Lime_Diet_Coke.jpg
Manicotti.jpg
Mcintosh_Apples.jpg
Mint.jpg
Mio_blueberry_lemonade.jpg
Nectarines.jpg
NonDairy_creamer.jpg
Onion.jpg
Organic_plain_whole_milk_yogurt.jpg
Pantene_shampoo.jpg
Paper_towels.jpg
Peanutbutter.jpg
Peanut_butter.jpg
Poland_Springs_water.jpg
Potato_salad.jpg
Pre-made_pizza_crust.jpg
Pumpkin.jpg
Ravioli.jpg
Rice.jpg
Rice_cakes.jpg
Salted_Almonds.jpg
Sandwich_Thins/Flats.jpg
Shredded_mozzarella_cheese.jpg
slim.jpg
Slim_Cow_ice_cream.jpg
“Slim_Cow”_ice_cream_(chocolate,_vanilla,_cookies_'n_cream).jpg
Small_pasta_shells.jpg
Soups.jpg
Sour_cream.jpg
Soy_milk.jpg
Spaghetti.jpg
Spaghetti_sauce.jpg
Special_K_with_strawberries.jpg
Splenda.jpg
Strawberries.jpg
Sunscreen.jpg
Tide_(high_efficiency).jpg
Tofu.jpg
Toilet_tissue.jpg
Tortellini_stuffed_with_chicken.jpg
Tylenol_XL.jpg
Whole_wheat_sliced_bread.jpg
EOF
